export enum ServerSideRoutes {
    APP = '/api',
    LOGOUT = `${ServerSideRoutes.APP}/logout`,
    ADMIN_TEACHERS = `${ServerSideRoutes.APP}/admin/teachers`,
    ADMIN_TEACHERS_UPLOAD = `${ServerSideRoutes.APP}/admin/teachers/upload`,
    ADMIN_TEACHERS_TEMPLATE = `${ServerSideRoutes.APP}/admin/teachers/template`,
    ADMIN_REGIONS = `${ServerSideRoutes.APP}/admin/regions`,
    ADMIN_SCHOOLS = `${ServerSideRoutes.APP}/admin/schools`,
    ADMIN_DASHBOARD = `${ServerSideRoutes.APP}/admin/dashboard`,
    TEACHER_DASHBOARD = `${ServerSideRoutes.APP}/teacher/dashboard`,
    TEACHER_STUDENTS = `${ServerSideRoutes.APP}/teacher/students`,
    TEACHER_STUDENTS_UPLOAD = `${ServerSideRoutes.APP}/teacher/students/upload`,
    TEACHER_STUDENTS_TEMPLATE = `${ServerSideRoutes.APP}/teacher/students/template`,
    STUDENT_LOGIN = `${ServerSideRoutes.APP}/student/login`,
    STUDENT_PROFILE = `${ServerSideRoutes.APP}/student/profile`,
    STUDENT_EXAM_INSTRUCTIONS = `${ServerSideRoutes.APP}/student/exam/instructions`,
    STUDENT_EXAM_QUESTIONS = `${ServerSideRoutes.APP}/student/exam/questions`,
    STUDENT_EXAM_SAVE_ANSWER = `${ServerSideRoutes.APP}/student/exam/save-answer`,
    STUDENT_EXAM_SUBMIT = `${ServerSideRoutes.APP}/student/exam/submit`,
    STORE_AUTH_TOKEN = `${ServerSideRoutes.APP}/store-auth-token`,
    STORE_USER_DETAIL_ROUTE = `${ServerSideRoutes.APP}/store-user-details`,
    SUBJECTS = `${ServerSideRoutes.APP}/subjects`,
    GRADE_GROUP = `${ServerSideRoutes.APP}/grade-group`,
    GRADES = `${ServerSideRoutes.APP}/grades`,
    //
}
