export enum ServerSideRoutes {
    APP = '/api',
    LOGOUT = `${ServerSideRoutes.APP}/logout`,
    ADMIN_TEACHERS = `${ServerSideRoutes.APP}/admin/teachers`,
    ADMIN_TEACHERS_UPLOAD = `${ServerSideRoutes.APP}/admin/teachers/upload`,
    ADMIN_REGIONS = `${ServerSideRoutes.APP}/admin/regions`,
    ADMIN_SCHOOLS = `${ServerSideRoutes.APP}/admin/schools`,
    ADMIN_DASHBOARD = `${ServerSideRoutes.APP}/admin/dashboard`,
    ADMIN_DOWNLOAD_REPORT = `${ServerSideRoutes.APP}/admin/download-report`,
    ADMIN_QUESTIONS = `${ServerSideRoutes.APP}/admin/questions`,
    ADMIN_QUESTIONS_GENERATE = `${ServerSideRoutes.APP}/admin/questions/generate`,
    ADMIN_REVIEWERS = `${ServerSideRoutes.APP}/admin/reviewers`,
    REVIEWER_DASHBOARD = `${ServerSideRoutes.APP}/reviewer/dashboard`,
    REVIEWER_QUESTIONS = `${ServerSideRoutes.APP}/reviewer/questions`,
    TEACHER_DASHBOARD = `${ServerSideRoutes.APP}/teacher/dashboard`,
    TEACHER_STUDENTS = `${ServerSideRoutes.APP}/teacher/students`,
    TEACHER_STUDENTS_UPLOAD = `${ServerSideRoutes.APP}/teacher/students/upload`,
    STUDENT_LOGIN = `${ServerSideRoutes.APP}/student/login`,
    STUDENT_PROFILE = `${ServerSideRoutes.APP}/student/profile`,
    STUDENT_EXAM_INSTRUCTIONS = `${ServerSideRoutes.APP}/student/exam/instructions`,
    STUDENT_EXAM_START = `${ServerSideRoutes.APP}/student/exam/start`,
    STUDENT_EXAM_QUESTIONS = `${ServerSideRoutes.APP}/student/exam/questions`,
    STUDENT_EXAM_SAVE_ANSWER = `${ServerSideRoutes.APP}/student/exam/save-answer`,
    STUDENT_EXAM_SUBMIT = `${ServerSideRoutes.APP}/student/exam/submit`,
    STORE_AUTH_TOKEN = `${ServerSideRoutes.APP}/store-auth-token`,
    STORE_USER_DETAIL_ROUTE = `${ServerSideRoutes.APP}/store-user-details`,
    SUBJECTS = `${ServerSideRoutes.APP}/subjects`,
    GRADE_GROUP = `${ServerSideRoutes.APP}/grade-group`,
    GRADES = `${ServerSideRoutes.APP}/grades`,
    GRADES_BY_GRADE_GROUP = `${ServerSideRoutes.APP}/grades/grade-group`,
    SUBJECTS_BY_GRADE_GROUP = `${ServerSideRoutes.APP}/subjects/grade-group`,
    SUBJECTS_BY_GRADE = `${ServerSideRoutes.APP}/subjects/grade`,
    COMPETENCIES_LIST = `${ServerSideRoutes.APP}/competencies-list`,
    ADMIN_REPORTS = `${ServerSideRoutes.APP}/admin/reports`,
    //
}
