import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { Inter } from 'next/font/google';

import Providers from './_providers';

const inter = Inter({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Lat Portal',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: ReactNode;
}>) => (
    <html lang='en'>
        <body className={`${inter.style.fontFamily}`} style={{ margin: 0 }}>
            <Providers>{children}</Providers>
        </body>
    </html>
);

export default RootLayout;
