export const API_URL = `${process.env.NEXT_PUBLIC_APP_URL?.trim() ?? ''}api/v1`;

export const API_ROUTES = {
    adminActionRequired: `${API_URL}/admin/action-required`,
    adminApprove: `${API_URL}/admin/approve`,
    adminAssignSiteVisitor: `${API_URL}/admin/assign-site-visitor`,
    adminDashboard: `${API_URL}/admin/dashboard`,
    adminGlobalCounters: `${API_URL}/admin/global-counters`,
    adminLedgerSummary: `${API_URL}/admin/ledger-summary`,
    adminLeads: `${API_URL}/admin/leads`,
    adminPaymentOverview: `${API_URL}/admin/payment-overview`,
    adminPipelineStages: `${API_URL}/admin/pipeline-stages`,
    adminReject: `${API_URL}/admin/reject`,
    adminSetDealAmount: `${API_URL}/admin/set-deal-amount`,
    adminSiteVisitors: `${API_URL}/admin/site-visitors`,
    adminTeachers: `${API_URL}/teachers`,
    uploadTeachers: `${API_URL}/teachers/bulk`,
    dashboardSummary: `${API_URL}/admin/dashboard/summary`,
    teacherDashboard: `${API_URL}/teacher/dashboard`,
    teacherStudents: `${API_URL}/teacher/students`,
    regions: `${API_URL}/regions`,
    schools: (regionId: string) => `${API_URL}/regions/${regionId}/schools`,
    subjects: `${API_URL}/subjects`,
    studentExamCheck: `${API_URL}/students/exam/check`,
    gradeGroup: `${API_URL}/grade-group`,
    grades: `${API_URL}/grades`,
    gradesByGradeGroup: (id: string) => `${API_URL}/grades/grade-group/${id}`,
    subjectsByGradeGroup: (id: string) => `${API_URL}/subjects/grade-group/${id}`,
    competenciesList: `${API_URL}/competencies-list`,
    adminQuestions: `${API_URL}/questions`,
    generateQuestions: `${API_URL}/generate-batch`,
    login: `${API_URL}/login`,
};
